/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeklifFormuRouteImport } from './routes/teklif-formu'
import { Route as HakkimizdaIndexRouteImport } from './routes/hakkimizda.index'
import { Route as HakkimizdaTemizlikSureciRouteImport } from './routes/hakkimizda.temizlik-sureci'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeklifFormuRoute = TeklifFormuRouteImport.update({
  id: '/teklif-formu',
  path: '/teklif-formu',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimizdaIndexRoute = HakkimizdaIndexRouteImport.update({
  id: '/hakkimizda/',
  path: '/hakkimizda/',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimizdaTemizlikSureciRoute =
  HakkimizdaTemizlikSureciRouteImport.update({
    id: '/hakkimizda/temizlik-sureci',
    path: '/hakkimizda/temizlik-sureci',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/teklif-formu': typeof TeklifFormuRoute
  '/hakkimizda/temizlik-sureci': typeof HakkimizdaTemizlikSureciRoute
  '/hakkimizda/': typeof HakkimizdaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/teklif-formu': typeof TeklifFormuRoute
  '/hakkimizda/temizlik-sureci': typeof HakkimizdaTemizlikSureciRoute
  '/hakkimizda': typeof HakkimizdaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/teklif-formu': typeof TeklifFormuRoute
  '/hakkimizda/temizlik-sureci': typeof HakkimizdaTemizlikSureciRoute
  '/hakkimizda/': typeof HakkimizdaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/teklif-formu' | '/hakkimizda/temizlik-sureci' | '/hakkimizda/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/teklif-formu' | '/hakkimizda/temizlik-sureci' | '/hakkimizda'
  id:
    | '__root__'
    | '/'
    | '/teklif-formu'
    | '/hakkimizda/temizlik-sureci'
    | '/hakkimizda/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TeklifFormuRoute: typeof TeklifFormuRoute
  HakkimizdaTemizlikSureciRoute: typeof HakkimizdaTemizlikSureciRoute
  HakkimizdaIndexRoute: typeof HakkimizdaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teklif-formu': {
      id: '/teklif-formu'
      path: '/teklif-formu'
      fullPath: '/teklif-formu'
      preLoaderRoute: typeof TeklifFormuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda/': {
      id: '/hakkimizda/'
      path: '/hakkimizda'
      fullPath: '/hakkimizda/'
      preLoaderRoute: typeof HakkimizdaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda/temizlik-sureci': {
      id: '/hakkimizda/temizlik-sureci'
      path: '/hakkimizda/temizlik-sureci'
      fullPath: '/hakkimizda/temizlik-sureci'
      preLoaderRoute: typeof HakkimizdaTemizlikSureciRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TeklifFormuRoute: TeklifFormuRoute,
  HakkimizdaTemizlikSureciRoute: HakkimizdaTemizlikSureciRoute,
  HakkimizdaIndexRoute: HakkimizdaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
