/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeklifFormuRouteImport } from './routes/teklif-formu'
import { Route as HakkimizdaIndexRouteImport } from './routes/hakkimizda.index'
import { Route as HakkimizdaSikcaSorulanSorularRouteImport } from './routes/hakkimizda.sikca-sorulan-sorular'
import { Route as HakkimizdaTemizlikSureciRouteImport } from './routes/hakkimizda.temizlik-sureci'
import { Route as HizmetBolgeleriIndexRouteImport } from './routes/hizmet-bolgeleri.index'
import { Route as HizmetlerimizIndexRouteImport } from './routes/hizmetlerimiz.index'
import { Route as HizmetlerimizSlugRouteImport } from './routes/hizmetlerimiz.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeklifFormuRoute = TeklifFormuRouteImport.update({
  id: '/teklif-formu',
  path: '/teklif-formu',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimizdaIndexRoute = HakkimizdaIndexRouteImport.update({
  id: '/hakkimizda/',
  path: '/hakkimizda/',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimizdaSikcaSorulanSorularRoute =
  HakkimizdaSikcaSorulanSorularRouteImport.update({
    id: '/hakkimizda/sikca-sorulan-sorular',
    path: '/hakkimizda/sikca-sorulan-sorular',
    getParentRoute: () => rootRouteImport,
  } as any)
const HakkimizdaTemizlikSureciRoute =
  HakkimizdaTemizlikSureciRouteImport.update({
    id: '/hakkimizda/temizlik-sureci',
    path: '/hakkimizda/temizlik-sureci',
    getParentRoute: () => rootRouteImport,
  } as any)
const HizmetBolgeleriIndexRoute = HizmetBolgeleriIndexRouteImport.update({
  id: '/hizmet-bolgeleri/',
  path: '/hizmet-bolgeleri/',
  getParentRoute: () => rootRouteImport,
} as any)
const HizmetlerimizIndexRoute = HizmetlerimizIndexRouteImport.update({
  id: '/hizmetlerimiz/',
  path: '/hizmetlerimiz/',
  getParentRoute: () => rootRouteImport,
} as any)
const HizmetlerimizSlugRoute = HizmetlerimizSlugRouteImport.update({
  id: '/hizmetlerimiz/$slug',
  path: '/hizmetlerimiz/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/teklif-formu': typeof TeklifFormuRoute
  '/hakkimizda/sikca-sorulan-sorular': typeof HakkimizdaSikcaSorulanSorularRoute
  '/hakkimizda/temizlik-sureci': typeof HakkimizdaTemizlikSureciRoute
  '/hizmetlerimiz/$slug': typeof HizmetlerimizSlugRoute
  '/hakkimizda/': typeof HakkimizdaIndexRoute
  '/hizmet-bolgeleri/': typeof HizmetBolgeleriIndexRoute
  '/hizmetlerimiz/': typeof HizmetlerimizIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/teklif-formu': typeof TeklifFormuRoute
  '/hakkimizda/sikca-sorulan-sorular': typeof HakkimizdaSikcaSorulanSorularRoute
  '/hakkimizda/temizlik-sureci': typeof HakkimizdaTemizlikSureciRoute
  '/hizmetlerimiz/$slug': typeof HizmetlerimizSlugRoute
  '/hakkimizda': typeof HakkimizdaIndexRoute
  '/hizmet-bolgeleri': typeof HizmetBolgeleriIndexRoute
  '/hizmetlerimiz': typeof HizmetlerimizIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/teklif-formu': typeof TeklifFormuRoute
  '/hakkimizda/sikca-sorulan-sorular': typeof HakkimizdaSikcaSorulanSorularRoute
  '/hakkimizda/temizlik-sureci': typeof HakkimizdaTemizlikSureciRoute
  '/hizmetlerimiz/$slug': typeof HizmetlerimizSlugRoute
  '/hakkimizda/': typeof HakkimizdaIndexRoute
  '/hizmet-bolgeleri/': typeof HizmetBolgeleriIndexRoute
  '/hizmetlerimiz/': typeof HizmetlerimizIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/teklif-formu'
    | '/hakkimizda/sikca-sorulan-sorular'
    | '/hakkimizda/temizlik-sureci'
    | '/hizmetlerimiz/$slug'
    | '/hakkimizda/'
    | '/hizmet-bolgeleri/'
    | '/hizmetlerimiz/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/teklif-formu'
    | '/hakkimizda/sikca-sorulan-sorular'
    | '/hakkimizda/temizlik-sureci'
    | '/hizmetlerimiz/$slug'
    | '/hakkimizda'
    | '/hizmet-bolgeleri'
    | '/hizmetlerimiz'
  id:
    | '__root__'
    | '/'
    | '/teklif-formu'
    | '/hakkimizda/sikca-sorulan-sorular'
    | '/hakkimizda/temizlik-sureci'
    | '/hizmetlerimiz/$slug'
    | '/hakkimizda/'
    | '/hizmet-bolgeleri/'
    | '/hizmetlerimiz/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TeklifFormuRoute: typeof TeklifFormuRoute
  HakkimizdaSikcaSorulanSorularRoute: typeof HakkimizdaSikcaSorulanSorularRoute
  HakkimizdaTemizlikSureciRoute: typeof HakkimizdaTemizlikSureciRoute
  HizmetlerimizSlugRoute: typeof HizmetlerimizSlugRoute
  HakkimizdaIndexRoute: typeof HakkimizdaIndexRoute
  HizmetBolgeleriIndexRoute: typeof HizmetBolgeleriIndexRoute
  HizmetlerimizIndexRoute: typeof HizmetlerimizIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teklif-formu': {
      id: '/teklif-formu'
      path: '/teklif-formu'
      fullPath: '/teklif-formu'
      preLoaderRoute: typeof TeklifFormuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda/': {
      id: '/hakkimizda/'
      path: '/hakkimizda'
      fullPath: '/hakkimizda/'
      preLoaderRoute: typeof HakkimizdaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda/sikca-sorulan-sorular': {
      id: '/hakkimizda/sikca-sorulan-sorular'
      path: '/hakkimizda/sikca-sorulan-sorular'
      fullPath: '/hakkimizda/sikca-sorulan-sorular'
      preLoaderRoute: typeof HakkimizdaSikcaSorulanSorularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda/temizlik-sureci': {
      id: '/hakkimizda/temizlik-sureci'
      path: '/hakkimizda/temizlik-sureci'
      fullPath: '/hakkimizda/temizlik-sureci'
      preLoaderRoute: typeof HakkimizdaTemizlikSureciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hizmet-bolgeleri/': {
      id: '/hizmet-bolgeleri/'
      path: '/hizmet-bolgeleri'
      fullPath: '/hizmet-bolgeleri/'
      preLoaderRoute: typeof HizmetBolgeleriIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hizmetlerimiz/': {
      id: '/hizmetlerimiz/'
      path: '/hizmetlerimiz'
      fullPath: '/hizmetlerimiz/'
      preLoaderRoute: typeof HizmetlerimizIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hizmetlerimiz/$slug': {
      id: '/hizmetlerimiz/$slug'
      path: '/hizmetlerimiz/$slug'
      fullPath: '/hizmetlerimiz/$slug'
      preLoaderRoute: typeof HizmetlerimizSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TeklifFormuRoute: TeklifFormuRoute,
  HakkimizdaSikcaSorulanSorularRoute: HakkimizdaSikcaSorulanSorularRoute,
  HakkimizdaTemizlikSureciRoute: HakkimizdaTemizlikSureciRoute,
  HizmetlerimizSlugRoute: HizmetlerimizSlugRoute,
  HakkimizdaIndexRoute: HakkimizdaIndexRoute,
  HizmetBolgeleriIndexRoute: HizmetBolgeleriIndexRoute,
  HizmetlerimizIndexRoute: HizmetlerimizIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
